### ISSUE TITLE
Add issue and pull request templates

### ISSUE THREAD

**Issue by Olavhaasie** [project-march/.github#2]
Add multiple issue and pull request templates which can be used organization wide.

See https://help.github.com/en/articles/about-issue-and-pull-request-templates for more information.

**Comment by Ishadijcks** [comment]
Does this repo add it for the entire organization?

**Comment by Olavhaasie** [comment]
Yes, see "[Creating a default community health file for your organization](https://help.github.com/en/articles/creating-a-default-community-health-file-for-your-organization)"

**Comment by Ishadijcks** [comment]
Neat
